"""empty message

Revision ID: fa5a016e5096
Revises: 
Create Date: 2017-12-16 18:20:13.575322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5a016e5096'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('exercise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'set', 'exercise', ['exercise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'set', type_='foreignkey')
    op.drop_column('set', 'exercise_id')
    # ### end Alembic commands ###
